//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupiedPlace
    {
        public int IdOccupiedPlaces { get; set; }
        public int HallId { get; set; }
        public string NumberPlace { get; set; }
    
        public virtual Hall Hall { get; set; }
    }
}
